source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def firestack_pods
  [
    'Firebase',
    'Firebase/Core',
    'Firebase/Auth',
    'Firebase/Storage',
    'Firebase/Database',
    'Firebase/RemoteConfig',
    'Firebase/Messaging'
  ].each do |lib|
    pod lib
  end
end

target 'FirestackApp' do
  firestack_pods
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
end
